##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-indicator-applet
    - gcc
    - git
    - gtk3
    - intltool
    - libindicator-gtk3
    - make
    - mate-common
    - mate-panel
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-indicator-applet
    - git
    - intltool
    - libgtk-3-dev
    - libindicator3-dev
    - libmate-panel-applet-dev
    - libtool
    - libx11-dev
    - libxml2-dev
    - make
    - mate-common

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-indicator-applet.git
    - gcc
    - git
    - gtk3-devel
    - libindicator-gtk3-devel
    - make
    - mate-common
    - mate-panel-devel
    - redhat-rpm-config

  ubuntu:
    - git
    - intltool
    - libgtk-3-dev
    - libido3-0.1-dev
    - libindicator3-dev
    - libmate-panel-applet-dev
    - libtool
    - libx11-dev
    - libxml2-dev
    - make
    - mate-common

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-indicator-applet-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
